### ISSUE TITLE
3.x – Cannot import

### ISSUE THREAD

**Issue by wjdp** [Shopify/liquid-c#32]
I'm using 3.x (for Jekyll). With a gemfile of:

```Gemfile
gem 'liquid', github: 'Shopify/liquid', branch: '3-0-stable'
gem 'liquid-c', github: 'Shopify/liquid-c', branch: '3-0-stable'
```

I get the following when trying to import the library:

```
irb(main):001:0> require 'liquid/c'
NameError: uninitialized constant Liquid::BlockBody
Did you mean?  Liquid::Block
	from /home/will/.bundle/ruby/2.3.0/liquid-c-368d76cde51d/lib/liquid/c.rb:3:in `require'
	from /home/will/.bundle/ruby/2.3.0/liquid-c-368d76cde51d/lib/liquid/c.rb:3:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
```

**Comment by fw42** [comment]
Are you sure you are on the latest revision (8d19fdde7f48347107632f91efb84526aa4972c4) of the `3-0-stable` branch of the `liquid` repository? Try `bundle update liquid`?

**Comment by wjdp** [comment]
Yep

```
~/l/liquid-c ❯❯❯ bundle update liquid
The git source `git://github.com/Shopify/liquid.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/Shopify/liquid-c.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/Shopify/liquid.git
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using liquid 3.0.6 from git://github.com/Shopify/liquid.git (at 3-0-stable@8d19fdd)
Using bundler 1.13.6
Using liquid-c 3.0.0 from git://github.com/Shopify/liquid-c.git (at 3-0-stable@368d76c)
Bundle updated!
~/l/liquid-c ❯❯❯ less Gemfile
source 'https://rubygems.org'

gem 'liquid', github: 'Shopify/liquid', branch: '3-0-stable'
gem 'liquid-c', github: 'Shopify/liquid-c', branch: '3-0-stable'
~/l/liquid-c ❯❯❯ bundle exec irb
irb(main):001:0> require 'liquid/c'
NameError: uninitialized constant Liquid::BlockBody
Did you mean?  Liquid::Block
	from /home/will/.bundle/ruby/2.3.0/liquid-c-368d76cde51d/lib/liquid/c.rb:3:in `require'
	from /home/will/.bundle/ruby/2.3.0/liquid-c-368d76cde51d/lib/liquid/c.rb:3:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
irb(main):002:0> 
```

**Comment by fw42** [comment]
https://github.com/Shopify/liquid/pull/874 should address this.

**Comment by wjdp** [comment]
Fab, thanks for looking into this.

**Comment by dylanahsmith** [comment]
Shopify/liquid#874 was closed a long time ago, so going to close this
